<?php
return [
	/*
	|===============================================
	| macOSLAPS
	|===============================================
	|
	| macOSLAPS module requires an encryption key before it will work. The
	| key can be generated by going to the macOSLAPS Management page under
	| the Admin tab. laps_password_decrypt_enabled controls all global password
	| decrypting. If it is set to FALSE, MunkiReport will never return
	| plaintext password. view_laps_password is an array of users that you
	| want to grant permission to view the passwords. If commented out all
	| users will be able to view the passwords.
	|
	*/

	$conf['laps_encryption_key'] =  getenv_default('LAPS_ENCRYPTION_KEY', ''),
	$conf['laps_password_decrypt_enabled'] = getenv_default('LAPS_PASSWORD_DECRYPT_ENABLED', TRUE, 'bool'),
	//$conf['view_laps_password'] = getenv_default('VIEW_LAPS_PASSWORD', [''], 'array'),
];
